// Script to parse CSV and generate SQL updates for control summaries
// Run this manually to generate the SQL statements

const csvData = `Control Name,Description,Category,Points,Popularity,Actions,Systems and Assets at Risk,Responsible Role,Control Authors,Description Summary
Electrical Room Presence of Water Monitoring,"The contractor and developer will ensure that water sensors are installed in electrical rooms to provide real-time alerts in the event of water presence. These sensors will be strategically placed to detect any water accumulation, helping to mitigate risks of water damage to sensitive electrical equipment. The installation locations and minimum required quantities of water sensors will be specified in the Water Mitigation Plan, which will be maintained by the contractor and developer. This proactive approach ensures early detection and prompt response to any water-related issues, safeguarding the electrical infrastructure and enhancing overall system reliability.",Presence of Water Monitoring,5,5,"Installation - The water mitigation provider will install water sensors in electrical rooms for real-time water detection.
Placement - Sensors will be strategically placed, with location and quantity outlined in the Water Mitigation Plan.Maintenance - The Water Mitigation Plan will be maintained and reviewed to ensure effective sensor functionality.",Electrical Rooms,Developer,Wint.ai,Electrical Room Presence of Water Monitoring protects Electrical Rooms using presence of water monitoring.
Mechanical Room Presence of Water Monitoring,"The contractor and developer will ensure that water sensors are installed in Mechanical Rooms to provide real-time alerts in the event of water presence. These sensors will be strategically placed to detect any water accumulation, helping to mitigate risks of water damage. The installation locations and minimum required quantities of water sensors will be specified in the Water Mitigation Plan, which will be maintained by the contractor and developer. This proactive approach ensures early detection and prompt response to any water-related issues, safeguarding the infrastructure and enhancing overall system reliability. ",Presence of Water Monitoring,10,5,"Installation - The water mitigation provider will install water sensors in mechanical rooms for real-time water detection.
Placement - Sensors will be strategically placed, with location and quantity outlined in the Water Mitigation Plan.Maintenance - The Water Mitigation Plan will be maintained and reviewed to ensure effective sensor functionality.","Domestic Cold Water, Domestic Hot Water, Fire Suppression System, Main City Water Supply, Mechanical Risers, Mechanical Rooms",Developer,Wint.ai,"Mechanical Room Presence of Water Monitoring protects Domestic Cold Water, Domestic Hot Water using presence of water monitoring."
Mechanical Risers Presence of Water Monitoring,"The contractor and developer will ensure that water sensors are installed in the mechanical risers to provide real-time alerts in the event of water presence. These sensors will be strategically placed to detect any water accumulation, helping to mitigate risks of water damage. The installation locations and minimum required quantities of water sensors will be specified in the Water Mitigation Plan, which will be maintained by the contractor and developer. This proactive approach ensures early detection and prompt response to any water-related issues, safeguarding the infrastructure and enhancing overall system reliability.",Presence of Water Monitoring,6,5,"Installation - The water mitigation provider will install water sensors in mechanical risers for real-time water detection.
Placement - Sensors will be strategically placed, with location and quantity outlined in the Water Mitigation Plan.
Maintenance - The Water Mitigation Plan will be maintained and reviewed to ensure effective sensor functionality.
","Domestic Cold Water, Domestic Hot Water, Fire Suppression System, Mechanical Risers, Mechanical Rooms",Developer,Wint.ai,"Mechanical Risers Presence of Water Monitoring protects Domestic Cold Water, Domestic Hot Water using presence of water monitoring."
Main Electrical Riser Presence of Water Monitoring,"The contractor and developer will ensure that water sensors are installed near the main electrical risers to provide real-time alerts in the event of water presence. These sensors will be strategically placed to detect any water accumulation, helping to mitigate risks of water damage to sensitive electrical infrastructure. The installation locations and minimum required quantities of water sensors will be specified in the Water Mitigation Plan, which will be maintained by the contractor and developer. This proactive approach ensures early detection and prompt response to any water-related issues, safeguarding the electrical infrastructure and enhancing overall system reliability.",Presence of Water Monitoring,5,5,"Installation - The water mitigation provider will install water sensors near the main electrical risers for real-time water detection.
Placement - Sensors will be strategically placed, with location and quantity outlined in the Water Mitigation Plan.
Maintenance - The Water Mitigation Plan will be maintained and reviewed to ensure effective sensor functionality.","Main Electrical Risers, Electrical Rooms",Developer,Wint.ai,Main Electrical Riser Presence of Water Monitoring protects Main Electrical Risers with presence of water monitoring.
Cold Domestic Water Abnormal Flow Monitoring,"The contractor and developer will ensure that flow meters are installed on the main water entry and cold domestic water supply systems to provide real-time monitoring and alerts in the event of abnormal water flow. These flow meters will be strategically placed to detect any unusual water consumption patterns, helping to mitigate risks of leaks, breaks, or wastage. The installation locations and minimum required quantities of flow meters will be specified in the Water Mitigation Plan, which will be maintained by the contractor and developer. This proactive approach ensures early detection and prompt response to any water-related issues, safeguarding the cold domestic water infrastructure and enhancing overall system reliability.",Abnormal Flow Monitoring,5,5,"Installation - The water mitigation provider will install flow meters on the cold domestic water supply for real-time flow monitoring.
Placement - Flow meters will be strategically placed, with location and quantity outlined in the Water Mitigation Plan.
Monitoring - Flow data will be continuously monitored to detect and alert for abnormal flow patterns.
Maintenance - The Water Mitigation Plan will be maintained and reviewed to ensure effective flow meter functionality.","Domestic Cold Water, Main City Water Supply",Developer,Wint.ai,Cold Domestic Water Abnormal Flow Monitoring safeguards Main City Water Supply and Domestic Cold Water with abnormal flow monitoring.
Hot Domestic Water Abnormal Flow Monitoring,"The contractor and developer will ensure that flow meters are installed on the main hot water supply riser after heating to provide real-time monitoring and alerts in the event of abnormal water flow. These flow meters will be strategically placed to detect any unusual water consumption patterns, helping to mitigate risks of leaks, breaks, or wastage. The installation locations and minimum required quantities of flow meters will be specified in the Water Mitigation Plan, which will be maintained by the contractor and developer. This proactive approach ensures early detection and prompt response to any water-related issues, safeguarding the hot domestic water infrastructure and enhancing overall system reliability.",Abnormal Flow Monitoring,5,5,"Installation - The water mitigation provider will install flow meters on the hot domestic water supply for real-time flow monitoring.
Placement - Flow meters will be strategically placed, with location and quantity outlined in the Water Mitigation Plan.
Monitoring - Flow data will be continuously monitored to detect and alert for abnormal flow patterns.
Maintenance - The Water Mitigation Plan will be maintained and reviewed to ensure effective flow meter functionality.","Domestic Hot Water, Mechanical Rooms",Developer,Wint.ai,Hot Domestic Water Abnormal Flow Monitoring safeguards Domestic Hot Water with abnormal flow monitoring.
Fire Suppression System Abnormal Flow Monitoring,"The contractor and developer will ensure that flow meters are installed on the fire suppression system to provide real-time monitoring and alerts in the event of abnormal water flow. These flow meters will be strategically placed to detect any unusual activation or water consumption patterns, helping to mitigate risks of leaks, breaks, or false discharges. The installation locations and minimum required quantities of flow meters will be specified in the Water Mitigation Plan, which will be maintained by the contractor and developer. This proactive approach ensures early detection and prompt response to any water-related issues, safeguarding the fire suppression infrastructure and enhancing overall system reliability.",Abnormal Flow Monitoring,5,5,"Installation - The water mitigation provider will install flow meters on the fire suppression system for real-time flow monitoring.
Placement - Flow meters will be strategically placed, with location and quantity outlined in the Water Mitigation Plan.
Monitoring - Flow data will be continuously monitored to detect and alert for abnormal flow patterns or discharge events.
Maintenance - The Water Mitigation Plan will be maintained and reviewed to ensure effective flow meter functionality.","Fire Suppression System, Mechanical Rooms",Developer,Wint.ai,Fire Suppression System Abnormal Flow Monitoring protects Fire Suppression System through abnormal flow monitoring.
Temporary Water Run Abnormal Flow Monitoring,"The contractor and developer will ensure that flow meters are installed on the temporary water runs to provide real-time monitoring and alerts in the event of abnormal water flow. These flow meters will be strategically placed to detect any unusual water consumption patterns, helping to mitigate risks of leaks, breaks, or unauthorized use during the construction phase. The installation locations and minimum required quantities of flow meters will be specified in the Water Mitigation Plan, which will be maintained by the contractor and developer. This proactive approach ensures early detection and prompt response to any water-related issues, safeguarding the temporary water infrastructure and enhancing overall system reliability.",Abnormal Flow Monitoring,6,5,"Installation - The water mitigation provider will install flow meters on the temporary water runs for real-time flow monitoring.
Placement - Flow meters will be strategically placed, with location and quantity outlined in the Water Mitigation Plan.
Monitoring - Flow data will be continuously monitored to detect and alert for abnormal flow patterns.
Maintenance - The Water Mitigation Plan will be maintained and reviewed to ensure effective flow meter functionality.",Temporary Water Run,Contractor,Wint.ai,Temporary Water Run Abnormal Flow Monitoring ensures Temporary Water Run safety via abnormal flow monitoring.
Main Riser Section Automatic Shut Open/Close Cold Domestic Water,"The contractor and developer will ensure that the main cold water riser is equipped with an automatic shut-off valve to provide immediate isolation of the water supply in the event of abnormal flow or detected leaks. This valve will be strategically placed at the main riser section and will be integrated with the flow monitoring system. When abnormal flow is detected, the valve will automatically close to prevent further water damage. The installation location will be specified in the Water Mitigation Plan, which will be maintained by the contractor and developer. This proactive approach ensures rapid response to water-related issues, safeguarding the cold domestic water infrastructure and enhancing overall system reliability.",Automatic Shut-Off,7,5,"Installation - The water mitigation provider will install an automatic shut-off valve on the main cold water riser.
Integration - The valve will be integrated with the flow monitoring system to enable automatic shut-off upon abnormal flow detection.
Testing - The valve will be tested regularly to ensure functionality and rapid response time.
Maintenance - The Water Mitigation Plan will be maintained and reviewed to ensure effective valve operation.","Domestic Cold Water, Main City Water Supply",Developer,Wint.ai,Main Riser Section Automatic Shut Open/Close for Cold Domestic Water uses automatic shut-off to protect Main City Water Supply and Domestic Cold Water.
Automatic Shut Off Temporary Water Run,"The contractor will ensure that temporary water runs are equipped with automatic shut-off valves to provide immediate isolation of the water supply in the event of abnormal flow or detected leaks. These valves will be strategically placed on each temporary water run and will be integrated with the flow monitoring system. When abnormal flow is detected, the valve will automatically close to prevent further water damage during the construction phase. The installation locations will be specified in the Water Mitigation Plan, which will be maintained by the contractor. This proactive approach ensures rapid response to water-related issues during construction, safeguarding the site and enhancing overall system reliability.",Automatic Shut-Off,10,5,"Installation - The water mitigation provider will install automatic shut-off valves on temporary water runs.
Integration - The valves will be integrated with the flow monitoring system to enable automatic shut-off upon abnormal flow detection.
Testing - The valves will be tested regularly to ensure functionality and rapid response time.
Maintenance - The Water Mitigation Plan will be maintained and reviewed to ensure effective valve operation.",Temporary Water Run,Contractor,Wint.ai,Automatic Shut-Off for Temporary Water Run uses automatic shut-off to safeguard Temporary Water Run.
Flood Control Measures,"The contractor and developer will implement flood control measures to protect the building from external water intrusion due to flooding events. These measures may include, but are not limited to, proper site grading, drainage systems, flood barriers, sump pumps, and waterproofing of below-grade areas. A 100-Year Flood and Wind Storm Report will inform the design and implementation of these measures. The specific measures to be implemented will be detailed in the Water Mitigation Plan, which will be maintained by the contractor and developer. This proactive approach ensures the building is protected from flood-related water damage, safeguarding all water systems and critical assets within the building.",Flood Control Measures,8,4,"Site Grading - Ensure proper site grading to direct water away from the building.
Drainage Systems - Install and maintain drainage systems (e.g., French drains, catch basins) to manage surface water.
Flood Barriers - Deploy temporary or permanent flood barriers where necessary.
Sump Pumps - Install sump pumps in below-grade areas to remove water accumulation.
Waterproofing - Apply waterproofing to below-grade walls and floors.
Flood Assessment - Utilize a 100-Year Flood and Wind Storm Report to inform flood control design.
Maintenance - The Water Mitigation Plan will detail and maintain all flood control measures.","Domestic Cold Water, Domestic Hot Water, Elevator Pits, Fire Suppression System, Main City Water Supply, Mechanical Risers, Mechanical Rooms, Sump Pits, Suites",Developer,Wint.ai,Flood Control Measures protect Main City Water Supply and all critical assets with flood control measures.
Floor Penetrations Water Seals,"The contractor and developer will ensure that all floor penetrations for water system piping are properly sealed to prevent water migration between floors in the event of a leak. These seals will be installed using approved fire-rated and water-resistant materials. The installation of floor penetration seals will be specified in the Water Mitigation Plan, which will be maintained by the contractor and developer. This proactive approach ensures that water leaks are contained to a single floor, minimizing the spread of water damage and protecting critical assets on lower floors.",Floor Penetrations Water Seals,5,4,"Seal Installation - Install water-resistant and fire-rated seals at all floor penetrations for water piping.
Material Specification - Use approved materials that meet fire and water resistance standards.
Inspection - Inspect seals during and after installation to ensure proper sealing.
Maintenance - The Water Mitigation Plan will detail the maintenance and inspection schedule for floor penetration seals.","Domestic Cold Water, Domestic Hot Water, Fire Suppression System, Main City Water Supply, Mechanical Risers",Developer,Wint.ai,Floor Penetrations Water Seals ensure Main City Water Supply and other systems' integrity through floor penetration water seals.
Heat trace and Insulation,"The contractor and developer will ensure that hot water piping in exposed or unheated areas is protected with heat trace and proper insulation to prevent freezing and subsequent pipe bursts. Heat trace systems will maintain a minimum temperature in the piping, and insulation will reduce heat loss. The installation locations and specifications will be detailed in the Water Mitigation Plan, which will be maintained by the contractor and developer. This proactive approach ensures the hot water system remains operational and protected from freezing conditions, safeguarding the infrastructure and preventing water damage.",Heat trace and Insulation,4,3,"Heat Trace Installation - Install heat trace systems on hot water piping in exposed or unheated areas.
Insulation Installation - Apply proper insulation to hot water piping to reduce heat loss and prevent freezing.
Temperature Monitoring - Monitor pipe temperatures to ensure heat trace systems are functioning effectively.
Maintenance - The Water Mitigation Plan will detail the maintenance and inspection schedule for heat trace and insulation systems.","Domestic Hot Water, Mechanical Rooms",Developer,Wint.ai,Heat Trace and Insulation maintain Domestic Hot Water system safety with heat trace and insulation.
Installation Integrity Joints Bolts and Piping,"The contractor and developer will ensure that all water system piping, joints, and bolted connections are installed with the highest integrity to prevent leaks and failures. This includes following manufacturer specifications, using proper torque values for bolted connections, and conducting quality control inspections during and after installation. The installation standards and inspection procedures will be detailed in the Water Mitigation Plan, which will be maintained by the contractor and developer. This proactive approach ensures the reliability and longevity of the water systems, minimizing the risk of leaks and water damage.",Installation Integrity Joints Bolts and Piping,5,5,"Installation Standards - Follow manufacturer specifications and industry best practices for piping installation.
Torque Specifications - Use proper torque values for all bolted connections to ensure leak-free joints.
Quality Control Inspections - Conduct inspections during and after installation to verify installation integrity.
Documentation - Document all inspections and installations in the Water Mitigation Plan.
Maintenance - The Water Mitigation Plan will detail ongoing inspection and maintenance procedures.","Domestic Cold Water, Domestic Hot Water, Fire Suppression System, Main City Water Supply",Developer,Wint.ai,Installation Integrity (Joints, Bolts, and Piping) ensures Main City Water Supply and other systems' integrity through joints, bolts, and piping checks.
Pressure Reducing Valve Maintenance Plan Safeguarding System Performance,"The contractor and developer will implement a comprehensive maintenance plan for pressure reducing valves (PRVs) to ensure they function correctly and maintain appropriate water pressure throughout the building. PRVs are critical to prevent over-pressurization, which can lead to leaks and pipe failures. The maintenance plan will include regular inspections, testing, and servicing of PRVs, as detailed in the Water Mitigation Plan, which will be maintained by the contractor and developer. This proactive approach ensures consistent water pressure, safeguarding the cold domestic water system and preventing pressure-related water damage.",Pressure Reducing Valve Maintenance Plan Safeguarding System Performance,5,4,"Inspection Schedule - Establish a regular inspection schedule for all pressure reducing valves.
Testing - Test PRVs to ensure they are maintaining the correct downstream pressure.
Servicing - Service or replace PRVs as needed based on inspection and testing results.
Documentation - Document all inspections, tests, and servicing activities in the Water Mitigation Plan.
Training - Train maintenance staff on PRV operation and troubleshooting.","Domestic Cold Water, Main City Water Supply",Developer,Wint.ai,Pressure Reducing Valve Maintenance Plan safeguards Main City Water Supply and Domestic Cold Water system performance through pressure reducing valve maintenance plan.
Proper Zoning Configuration Optimizing Pressure System,"The contractor and developer will ensure that the cold domestic water system is properly zoned to optimize pressure distribution and prevent over-pressurization in lower zones. Proper zoning involves dividing the water system into separate pressure zones, typically by floor or building section, and using pressure reducing valves or separate pumping systems for each zone. The zoning configuration will be detailed in the Water Mitigation Plan, which will be maintained by the contractor and developer. This proactive approach ensures consistent and safe water pressure throughout the building, preventing pressure-related leaks and water damage.",Proper Zoning Configuration Optimizing Pressure System,6,4,"Zoning Design - Design the cold domestic water system with appropriate pressure zones.
PRV Installation - Install pressure reducing valves or separate pumping systems for each zone.
Pressure Testing - Test each zone to ensure proper pressure levels are maintained.
Documentation - Document the zoning configuration and pressure testing results in the Water Mitigation Plan.
Maintenance - The Water Mitigation Plan will detail ongoing maintenance and monitoring of the zoning system.","Domestic Cold Water, Mechanical Rooms",Developer,Wint.ai,Proper Zoning Configuration optimizes Domestic Cold Water pressure system through proper zoning configuration.
Spill Kit,"The contractor and developer will ensure that spill kits are readily available in mechanical rooms and other areas where water systems are located. Spill kits should contain absorbent materials, containment barriers, and personal protective equipment to enable rapid response to small leaks or spills. The locations and contents of spill kits will be specified in the Water Mitigation Plan, which will be maintained by the contractor and developer. This proactive approach ensures that minor water incidents can be quickly contained and cleaned up, minimizing the potential for water damage.",Spill Kit,2,3,"Spill Kit Placement - Place spill kits in mechanical rooms and other areas with water systems.
Spill Kit Contents - Ensure spill kits contain absorbent materials, containment barriers, and personal protective equipment.
Training - Train staff on the location and use of spill kits.
Inspection - Regularly inspect and replenish spill kits to ensure they are ready for use.
Documentation - Document spill kit locations and inspection schedules in the Water Mitigation Plan.",Mechanical Rooms,Contractor,Wint.ai,Spill Kit provides Mechanical Rooms with spill kits for immediate response.
Suite Drains,"The contractor and developer will ensure that all suites are equipped with floor drains or other drainage provisions to quickly remove water in the event of a leak or overflow. Suite drains should be properly sized and connected to the building's drainage system. The installation and maintenance of suite drains will be specified in the Water Mitigation Plan, which will be maintained by the contractor and developer. This proactive approach ensures that water can be quickly removed from suites, minimizing water damage to suite finishes and contents, and preventing water migration to adjacent units or floors.",Suite Drains,4,3,"Drain Installation - Install floor drains or other drainage provisions in all suites.
Drain Sizing - Ensure drains are properly sized to handle potential water volumes.
Drain Maintenance - Maintain drains to ensure they remain clear and functional.
Testing - Test drains to ensure they are properly connected to the building drainage system.
Documentation - Document drain locations and maintenance schedules in the Water Mitigation Plan.",Suites,Developer,Wint.ai,Suite Drains safeguard Suites with properly installed suite drains.
Temporary Enclosures Plan,"The contractor will implement a temporary enclosures plan to protect the building interior and critical assets from water intrusion during construction. Temporary enclosures may include weatherproofing of building openings, installation of temporary roofing or tarpaulins, and protection of critical areas during wet work activities. The temporary enclosures plan will be detailed in the Water Mitigation Plan, which will be maintained by the contractor. This proactive approach ensures that the building interior is protected from weather-related water intrusion and construction-related water exposure, safeguarding all critical assets during the construction phase.",Temporary Enclosures Plan,5,4,"Weatherproofing - Weatherproof building openings (doors, windows, wall penetrations) to prevent water intrusion.
Temporary Roofing - Install temporary roofing or tarpaulins to protect unfinished areas.
Critical Area Protection - Protect critical assets (electrical rooms, mechanical rooms, etc.) during wet work activities.
Inspection - Regularly inspect temporary enclosures to ensure they are effective and maintained.
Documentation - Document the temporary enclosures plan and inspection schedules in the Water Mitigation Plan.","Electrical Rooms, Elevator Pits, Main Electrical Risers, Mechanical Risers, Mechanical Rooms, Sump Pits, Suites",Contractor,Wint.ai,Temporary Enclosures Plan protects all critical assets during construction with temporary enclosures plan.
Air Pressure or Water Tests in Plumbing System,"The contractor will conduct air pressure or water tests on the plumbing system before it is enclosed or concealed. These tests will verify the integrity of the piping system and identify any leaks or defects before they become concealed and difficult to access. The testing procedures and acceptance criteria will be specified in the Water Mitigation Plan, which will be maintained by the contractor. This proactive approach ensures that the plumbing system is leak-free before being put into service, preventing concealed leaks and subsequent water damage.",Air Pressure or Water Tests in Plumbing System,6,5,"Testing Procedure - Conduct air pressure or water tests on the plumbing system before concealment.
Acceptance Criteria - Define acceptance criteria for pressure tests based on code requirements and manufacturer specifications.
Leak Detection - Identify and repair any leaks or defects detected during testing.
Documentation - Document all testing procedures, results, and repairs in the Water Mitigation Plan.
Re-testing - Re-test any repaired sections to ensure they meet acceptance criteria.","Domestic Cold Water, Domestic Hot Water, Fire Suppression System, Main City Water Supply, Mechanical Risers, Mechanical Rooms",Contractor,Wint.ai,Air Pressure or Water Tests in Plumbing System ensure Main City Water Supply and other systems' integrity through air pressure or water tests.
Additional Fill Tests Ensuring Water System Integrity,"The contractor will conduct additional fill tests on the cold domestic water system beyond standard code requirements. These additional tests will involve filling the system with water and monitoring for pressure loss over an extended period (e.g., 24 hours). Additional fill tests provide a more rigorous assessment of system integrity compared to shorter-duration pressure tests. The testing procedures and acceptance criteria will be specified in the Water Mitigation Plan, which will be maintained by the contractor. This proactive approach ensures a higher level of confidence in the integrity of the cold domestic water system before it is put into service, preventing leaks and water damage.",Additional Fill Tests Ensuring Water System Integrity,7,4,"Extended Testing - Conduct fill tests on the cold domestic water system for an extended period (e.g., 24 hours).
Pressure Monitoring - Monitor system pressure throughout the fill test to detect any pressure loss.
Leak Detection - Identify and repair any leaks or defects detected during the fill test.
Acceptance Criteria - Define acceptance criteria for fill tests that are more stringent than standard code requirements.
Documentation - Document all testing procedures, results, and repairs in the Water Mitigation Plan.","Domestic Cold Water, Mechanical Rooms",Contractor,Wint.ai,Additional Fill Tests ensure Domestic Cold Water system integrity with additional fill tests.
Water Mitigation Equipment Acceptance Test,"The contractor and developer will conduct acceptance tests on all water mitigation equipment (sensors, flow meters, valves, monitoring systems) before the building is occupied. These tests will verify that all equipment is installed correctly, functioning as designed, and integrated with the monitoring system. The testing procedures and acceptance criteria will be specified in the Water Mitigation Plan, which will be maintained by the contractor and developer. This proactive approach ensures that all water mitigation equipment is operational and ready to protect the building before occupancy, providing confidence in the water damage prevention strategy.",Water Mitigation Equipment Acceptance Test,5,5,"Equipment Testing - Test all water mitigation equipment (sensors, flow meters, valves, monitoring systems) before occupancy.
Functional Verification - Verify that all equipment is functioning as designed and meeting performance specifications.
Integration Testing - Test the integration of all equipment with the central monitoring system.
Documentation - Document all testing procedures, results, and any corrective actions in the Water Mitigation Plan.
Training - Train building operations staff on the operation and maintenance of water mitigation equipment.","Domestic Cold Water, Domestic Hot Water, Electrical Rooms, Fire Suppression System, Main City Water Supply, Main Electrical Risers, Mechanical Risers, Mechanical Rooms, Temporary Water Run",Developer,Wint.ai,Water Mitigation Equipment Acceptance Test validates all systems with water mitigation equipment acceptance test.
Water Mitigation Equipment Labeling,"The contractor and developer will ensure that all water mitigation equipment (sensors, flow meters, valves, shut-off points) is clearly labeled to facilitate identification, operation, and maintenance. Labels should include equipment type, system served, and any relevant operating instructions. The labeling requirements will be specified in the Water Mitigation Plan, which will be maintained by the contractor and developer. This proactive approach ensures that building operations staff and emergency responders can quickly identify and operate water mitigation equipment, enabling rapid response to water-related incidents.",Water Mitigation Equipment Labeling,3,4,"Labeling Standards - Establish labeling standards for all water mitigation equipment.
Label Installation - Install labels on all sensors, flow meters, valves, and shut-off points.
Label Content - Include equipment type, system served, and operating instructions on labels.
Label Durability - Use durable labels that will remain legible throughout the life of the equipment.
Documentation - Document the labeling scheme in the Water Mitigation Plan.","Domestic Cold Water, Domestic Hot Water, Electrical Rooms, Fire Suppression System, Main City Water Supply, Main Electrical Risers, Mechanical Risers, Mechanical Rooms, Temporary Water Run",Developer,Wint.ai,Water Mitigation Equipment Labeling identifies all systems with water mitigation equipment labeling.
100-Year Flood and Wind Storm Report,"The developer will commission a 100-Year Flood and Wind Storm Report to assess the site's vulnerability to extreme weather events. This report will inform the design and implementation of flood control measures, building envelope design, and water mitigation strategies. The report will be maintained as part of the Water Mitigation Plan by the developer. This proactive approach ensures that the building is designed and constructed to withstand extreme weather events, minimizing the risk of water damage from flooding and wind-driven rain.",100-Year Flood and Wind Storm Report,4,3,"Report Commission - Commission a 100-Year Flood and Wind Storm Report from a qualified consultant.
Report Review - Review the report to identify site vulnerabilities and recommendations.
Design Integration - Integrate the report's findings and recommendations into the building design and flood control measures.
Documentation - Maintain the report as part of the Water Mitigation Plan.
Communication - Communicate relevant findings to the project team and stakeholders.","Domestic Cold Water, Domestic Hot Water, Electrical Rooms, Elevator Pits, Fire Suppression System, Main City Water Supply, Main Electrical Risers, Mechanical Risers, Mechanical Rooms, Sump Pits, Suites, Temporary Water Run",Developer,Wint.ai,100-Year Flood and Wind Storm Report assesses all assets with 100-year flood and wind storm report.
Historical Project Water Incident Reports,"The developer will review historical water incident reports from similar projects to identify common causes of water damage and inform the Water Mitigation Plan. This review will help the project team anticipate potential water-related issues and implement preventive measures. Historical incident reports can be obtained from insurance companies, industry associations, or internal company records. The findings from this review will be incorporated into the Water Mitigation Plan, which will be maintained by the developer. This proactive approach leverages lessons learned from past projects to prevent water damage on the current project.",Historical Project Water Incident Reports,3,3,"Report Collection - Collect historical water incident reports from similar projects.
Report Analysis - Analyze reports to identify common causes of water damage and contributing factors.
Lessons Learned - Extract lessons learned and best practices from the historical reports.
Plan Integration - Integrate lessons learned into the Water Mitigation Plan and project procedures.
Documentation - Document the findings and recommendations from the historical report review in the Water Mitigation Plan.","Domestic Cold Water, Domestic Hot Water, Electrical Rooms, Elevator Pits, Fire Suppression System, Main City Water Supply, Main Electrical Risers, Mechanical Risers, Mechanical Rooms, Sump Pits, Suites, Temporary Water Run",Developer,Wint.ai,Historical Project Water Incident Reports inform all systems with historical project water incident reports.
Pre-qualification of Envelope Systems,"The developer will pre-qualify all building envelope systems (curtain wall, roofing, waterproofing) by requiring manufacturers and installers to demonstrate a proven track record of performance and adherence to quality standards. Pre-qualification may include review of past projects, testing certifications, and installer training and certification requirements. The pre-qualification criteria will be specified in the Water Mitigation Plan, which will be maintained by the developer. This proactive approach ensures that only qualified and experienced manufacturers and installers are selected for envelope systems, reducing the risk of envelope failures and subsequent water intrusion.",Pre-qualification of Envelope Systems,6,4,"Pre-qualification Criteria - Establish pre-qualification criteria for envelope system manufacturers and installers.
Manufacturer Review - Review manufacturers' track records, testing certifications, and quality control procedures.
Installer Review - Review installers' experience, training certifications, and past project performance.
Selection Process - Use pre-qualification criteria to select qualified manufacturers and installers.
Documentation - Document the pre-qualification process and selected manufacturers/installers in the Water Mitigation Plan.","Electrical Rooms, Elevator Pits, Main Electrical Risers, Mechanical Risers, Mechanical Rooms, Sump Pits, Suites",Developer,Wint.ai,Pre-qualification of Envelope Systems ensures all critical assets with pre-qualification of envelope systems.
Water Mitigation Components Warranties and Insurance,"The developer will ensure that all water mitigation components (sensors, flow meters, valves, monitoring systems) are covered by manufacturer warranties and that the project has appropriate insurance coverage for water damage. Warranties should cover defects in materials and workmanship for a specified period. Insurance coverage should include builder's risk insurance and, if applicable, extended coverage for water damage. The warranty and insurance requirements will be detailed in the Water Mitigation Plan, which will be maintained by the developer. This proactive approach provides financial protection in the event of equipment failure or water damage, ensuring that repairs and remediation can be completed promptly.",Water Mitigation Components Warranties and Insurance,5,4,"Warranty Requirements - Specify minimum warranty requirements for all water mitigation components.
Warranty Collection - Collect and maintain all manufacturer warranties.
Insurance Coverage - Obtain appropriate insurance coverage for water damage, including builder's risk insurance.
Insurance Review - Review insurance policies to ensure adequate coverage for water-related risks.
Documentation - Document warranty and insurance information in the Water Mitigation Plan.","Domestic Cold Water, Domestic Hot Water, Electrical Rooms, Elevator Pits, Fire Suppression System, Main City Water Supply, Main Electrical Risers, Mechanical Risers, Mechanical Rooms, Sump Pits, Suites, Temporary Water Run",Developer,Wint.ai,Water Mitigation Components Warranties and Insurance protect all systems with water mitigation components warranties and insurance.`;

// Simple CSV parser function
function parseCSV(csv: string): Array<{name: string, summary: string, systems: string}> {
  const lines = csv.split('\n');
  const results: Array<{name: string, summary: string, systems: string}> = [];
  
  let currentLine = '';
  let inQuotes = false;
  let fields: string[] = [];
  let recordCount = 0;
  
  for (let i = 0; i < lines.length; i++) {
    currentLine += lines[i];
    
    // Count quotes to determine if we're inside a quoted field
    const quoteCount = (currentLine.match(/"/g) || []).length;
    inQuotes = quoteCount % 2 !== 0;
    
    if (!inQuotes) {
      // We have a complete record
      if (recordCount > 0) { // Skip header
        // Split by comma, but respect quoted fields
        const regex = /,(?=(?:(?:[^"]*"){2})*[^"]*$)/;
        fields = currentLine.split(regex).map(f => f.trim().replace(/^"|"$/g, ''));
        
        if (fields.length >= 10) {
          results.push({
            name: fields[0],
            summary: fields[9],
            systems: fields[6]
          });
        }
      }
      
      currentLine = '';
      recordCount++;
    } else {
      // Continue to next line
      currentLine += '\n';
    }
  }
  
  return results;
}

// Parse and generate SQL
const controls = parseCSV(csvData);
console.log('Parsed', controls.length, 'controls');

controls.forEach(control => {
  const escapedSummary = control.summary.replace(/'/g, "''");
  const escapedSystems = control.systems.replace(/'/g, "''");
  const escapedName = control.name.replace(/'/g, "''");
  
  console.log(`UPDATE mitigation_controls SET description_summary = '${escapedSummary}', systems_at_risk = '${escapedSystems}' WHERE name = '${escapedName}';`);
});
