-- 1. Table for tracking async export jobs
CREATE TABLE public.analysis_export_jobs (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  project_id UUID NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  analysis_request_id UUID REFERENCES public.analysis_requests(id) ON DELETE SET NULL,
  requested_by_user_id UUID NOT NULL,
  requested_by_email TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'complete', 'failed')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ,
  storage_path TEXT,
  download_filename TEXT,
  error_message TEXT,
  project_name_snapshot TEXT NOT NULL,
  source_type_snapshot TEXT NOT NULL,
  summary_data_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
  worker_id TEXT,
  attempts INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX idx_analysis_export_jobs_project_id ON public.analysis_export_jobs(project_id);
CREATE INDEX idx_analysis_export_jobs_status_created ON public.analysis_export_jobs(status, created_at) WHERE status = 'pending';
CREATE INDEX idx_analysis_export_jobs_user ON public.analysis_export_jobs(requested_by_user_id);

ALTER TABLE public.analysis_export_jobs ENABLE ROW LEVEL SECURITY;

-- View: project members + internal users
CREATE POLICY "Project members can view export jobs"
ON public.analysis_export_jobs
FOR SELECT
USING (
  EXISTS (
    SELECT 1 FROM public.projects p
    WHERE p.id = analysis_export_jobs.project_id
      AND (p.user_id = auth.uid() OR public.is_project_member(auth.uid(), p.id))
  )
  OR public.is_internal_user(auth.uid())
);

-- Insert: project members + internal users (so they can request exports)
CREATE POLICY "Project members can create export jobs"
ON public.analysis_export_jobs
FOR INSERT
WITH CHECK (
  requested_by_user_id = auth.uid()
  AND (
    EXISTS (
      SELECT 1 FROM public.projects p
      WHERE p.id = analysis_export_jobs.project_id
        AND (p.user_id = auth.uid() OR public.is_project_member(auth.uid(), p.id))
    )
    OR public.is_internal_user(auth.uid())
  )
);

-- No UPDATE/DELETE policies → only service_role (worker) can mutate

-- 2. Private storage bucket for generated DOCX exports
INSERT INTO storage.buckets (id, name, public)
VALUES ('analysis-exports', 'analysis-exports', false)
ON CONFLICT (id) DO NOTHING;

-- No public policies on storage.objects for this bucket → only service_role can read/write.
-- Users access files via signed URLs generated by the worker.

-- 3. Atomic claim RPC for the worker
-- Picks the oldest pending job, marks it processing, returns the row.
-- FOR UPDATE SKIP LOCKED makes this safe with multiple parallel workers.
CREATE OR REPLACE FUNCTION public.claim_next_export_job(p_worker_id TEXT)
RETURNS SETOF public.analysis_export_jobs
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN QUERY
  UPDATE public.analysis_export_jobs
  SET
    status = 'processing',
    started_at = now(),
    worker_id = p_worker_id,
    attempts = attempts + 1
  WHERE id = (
    SELECT id
    FROM public.analysis_export_jobs
    WHERE status = 'pending'
    ORDER BY created_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
  )
  RETURNING *;
END;
$$;

-- Only the service_role (worker) should call this.
REVOKE EXECUTE ON FUNCTION public.claim_next_export_job(TEXT) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.claim_next_export_job(TEXT) FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.claim_next_export_job(TEXT) TO service_role;